# Generated by Django 4.1.2 on 2022-10-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_breed', models.CharField(help_text='Pasirinkite katės veislę', max_length=200, verbose_name='Katės veislė')),
            ],
            options={
                'verbose_name': 'Katės veislė',
                'verbose_name_plural': 'Kačių veislės',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_breed', models.CharField(help_text='Pasirinkite šuns veislę', max_length=200, verbose_name='Šuns veislė')),
            ],
            options={
                'verbose_name': 'Šuns veislė',
                'verbose_name_plural': 'Šunų veislės',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Šuo'), ('1', 'Katė')], help_text='Pasirinkite gyvūno rūšį', max_length=1)),
                ('name', models.CharField(help_text='Nurodykite gyvūno vardą', max_length=200, null=True, verbose_name='Vardas')),
                ('status', models.CharField(choices=[('0', 'Dingo'), ('1', 'Rasta')], default='0', help_text='Pasirinkite gyvūno būseną', max_length=1, verbose_name='Būsena')),
                ('image', models.ImageField(help_text='Įkelkite gyvūno atvaizdą', null=True, upload_to='', verbose_name='Atvaizdas')),
                ('date', models.DateField(auto_now_add=True, help_text='Nurodykite radimo / dingimo datą', null=True, verbose_name='Data')),
                ('cat_breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.dog')),
                ('dog_breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.cat')),
            ],
            options={
                'verbose_name': 'Gyvūnas',
                'verbose_name_plural': 'Gyvūnai',
            },
        ),
    ]
