# Generated by Django 4.1.2 on 2022-10-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cat_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.cat'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dog_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.dog'),
        ),
    ]
