# Generated by Django 4.1.2 on 2022-10-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0004_alter_animal_cat_breed_alter_animal_dog_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_breed', models.CharField(help_text='Pasirinkite gyvūno rūšį', max_length=200, verbose_name='Rūšis')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(help_text='Pasirinkite gyvūno rūšį', on_delete=django.db.models.deletion.CASCADE, to='prieglauda.type'),
        ),
    ]
