# Generated by Django 4.1.2 on 2022-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0006_rename_dog_breed_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('0', 'Šuo'), ('1', 'Katė')], help_text='Pasirinkite gyvūno rūšį', max_length=1, verbose_name='Rūšis'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
