# Generated by Django 4.1.2 on 2022-10-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0007_alter_animal_type_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cat_breed',
            field=models.ForeignKey(blank=True, default='Mišri', help_text='Pasirinkite katės veislę', null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.cat'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('1', 'Dingo'), ('2', 'Rasta')], default='0', help_text='Pasirinkite gyvūno būseną', max_length=1, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('1', 'Šuo'), ('2', 'Katė')], help_text='Pasirinkite gyvūno rūšį', max_length=1, verbose_name='Rūšis'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(default='Mišri', help_text='Pasirinkite katės veislę', max_length=200, verbose_name='Katės veislė'),
        ),
    ]
