# Generated by Django 4.1.2 on 2022-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0010_alter_animal_cat_breed_alter_cat_cat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date',
            field=models.DateField(help_text='Nurodykite radimo / dingimo datą', null=True, verbose_name='Data'),
        ),
    ]
