# Generated by Django 4.1.2 on 2022-10-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0011_alter_animal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(help_text='Įkelkite gyvūno atvaizdą', null=True, upload_to='static/img', verbose_name='Atvaizdas'),
        ),
    ]
