# Generated by Django 4.1.2 on 2022-10-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0014_alter_animal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_breed', models.CharField(help_text='Pasirinkite gyvūno veislę', max_length=200, verbose_name='Veislė')),
            ],
            options={
                'verbose_name': 'Veislė',
                'verbose_name_plural': 'Veislės',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='cat_breed',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='dog_breed',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, help_text='Pasirinkite katės veislę', null=True, on_delete=django.db.models.deletion.CASCADE, to='prieglauda.breed'),
        ),
    ]
