# Generated by Django 4.1.2 on 2022-10-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0017_alter_animal_breed_delete_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(help_text='Pasirinkite gyvūno veislę', max_length=200, verbose_name='Veislė'),
        ),
    ]
