# Generated by Django 4.1.2 on 2022-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prieglauda', '0018_alter_animal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='Mišri', help_text='Pasirinkite gyvūno veislę', max_length=200, null=True, verbose_name='Veislė'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default='Be vardo', help_text='Nurodykite gyvūno vardą', max_length=200, null=True, verbose_name='Vardas'),
        ),
    ]
